<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>The Extended Integer (XInt) Library: Exceptions and the \c nothrow_integer Type</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Generated by Doxygen 1.7.1 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div class="navpath">
    <ul>
      <li><a class="el" href="index.html">The Extended Integer (XInt) Library</a>      </li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>Exceptions and the <code>nothrow_integer</code> Type </h1>  </div>
</div>
<div class="contents">
<p>Many things can go wrong while operating on an integer, such as divide-by-zero errors. Under normal circumstances, these result in exceptions, but exceptions sometimes make your code harder to follow, or even harder to write. That's why this library includes the <code>nothrow_integer</code> type.</p>
<p>The <code>xint::nothrow_integer</code> type has all of the functions that the <code>xint::integer</code> type does (they're generated from the same class template). When you use it, any exceptions generated by the library are caught internally, and the functions return a special value indicating failure (the <a class="el" href="nan.html">Not-a-Number</a> value on functions returning an integer_t type, otherwise the value will be noted in the documentation).</p>
<p>Here's an example, which can be found in the <code>examples</code> subdirectory as exceptions.cpp:</p>
<div class="fragment"><pre class="fragment">
<span class="preprocessor">#include &lt;<a class="code" href="integer_8hpp.html" title="Declares the arbitrary-length integer type.">boost/xint/integer.hpp</a>&gt;</span>
<span class="preprocessor">#include &lt;ostream&gt;</span>

<span class="keywordtype">int</span> main() {
    <span class="keyword">using namespace </span>std;
    <span class="keyword">using namespace </span>boost::xint;

    <span class="comment">// We&#39;ll wrap this in a try block for demonstration purposes, just to</span>
    <span class="comment">// prove that it doesn&#39;t throw an exception. You normally don&#39;t need a</span>
    <span class="comment">// try block if you&#39;re using nothrow_integers.</span>
    <span class="keywordflow">try</span> {
        <span class="comment">// Call the function(s) that may produce errors. The example call tries</span>
        <span class="comment">// to interpret an empty string as an integer, which would normally</span>
        <span class="comment">// throw an xint::exception::invalid_digit.</span>
        <a class="code" href="namespaceboost_1_1xint.html#adb761045d90aee163058a57489b51df2" title="The default arbitrary-length nothrow_integer type.">nothrow_integer</a> n = <a class="code" href="namespaceboost_1_1xint.html#adb761045d90aee163058a57489b51df2" title="The default arbitrary-length nothrow_integer type.">nothrow_integer</a>(<span class="stringliteral">&quot;&quot;</span>);

        <span class="comment">// n should be Not-a-Number, because there was an error but exceptions</span>
        <span class="comment">// are not allowed on nothrow_integers. This example code is fairly</span>
        <span class="comment">// useless, but it shows how to test for errors.</span>
        <span class="keywordflow">if</span> (n.is_nan()) {
            cout &lt;&lt; <span class="stringliteral">&quot;n is Not-a-Number, do some intelligent error handling here.&quot;</span>
                &lt;&lt; endl;
        } <span class="keywordflow">else</span> {
            <span class="comment">// This example code should never get to this block, but you would</span>
            <span class="comment">// usually put the normal program flow code here.</span>
            cout &lt;&lt; <span class="stringliteral">&quot;Error, n should be Not-a-Number and it isn&#39;t!&quot;</span> &lt;&lt; endl;
        }
    } <span class="keywordflow">catch</span> (std::exception&amp; e) {
        <span class="comment">// This example code should never get to this block, because exceptions</span>
        <span class="comment">// were blocked.</span>
        cout &lt;&lt; <span class="stringliteral">&quot;Error, nothrow_integer threw an exception!\n&quot;</span> &lt;&lt; e.what() &lt;&lt;
            endl;
    }
}
</pre></div> </div>
<hr>
<p><i>&copy; Copyright Chad Nelson, 2010-2011. Distributed under the Boost Software
License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
<a href=http://www.boost.org/LICENSE_1_0.txt>http://www.boost.org/LICENSE_1_0.txt</a>)
</i></p>
<p><i>Documentation generated on Wed Mar 9 2011 22:56:48 by&nbsp;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a>
1.7.1</small></address></i></p>
